app: sharedbread-backend-app

# For full config options, check the docs:
#    docs.serverless.com

service: sharedbread-backend


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}



functions:
  shoppingBasket:
    handler: shoppingBasket.handler
    events:
      - http:
          path: /basket/{id}
          method: GET
          cors: true
      - http:
          path: /basket
          method: POST
          cors: true 
      - http:
          path: /basket
          method: DELETE
          cors: true
  userProfileData:
    handler: userProfileData.handler
    events:
      - http:
          path: /profile
          method: POST
          cors: true
  addToShoppingBasket:
    handler: addToShoppingBasket.handler
    events:
      - http:
          path: /addToBasket
          method: POST
          cors: true    
