
# For full config options, check the docs:
#    docs.serverless.com

service: sharedbread-backend


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1



functions:
  shoppingBasket:
    handler: shoppingBasket.app
