org: bradleynichol
app: sharedbread-backend-app

# For full config options, check the docs:
#    docs.serverless.com

service: sharedbread-backend


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1



functions:
  shoppingBasket:
    handler: shoppingBasket.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: /basket
          method: GET
          cors: true
      - http:
          path: /basket
          method: POST
          cors: true 
      - http:
          path: /basket/{id}
          method: DELETE
          cors: true  
